In [3]:
%matplotlib inline
import SimpleITK as sitk
import matplotlib.pyplot as plt


# image type can represent a 2D, 3D and 4D image
# pixel types can be a scalar, multi-component vector or a run-length-encoded (RLE) "label"
# Dimension, pixel type and size specified at construction

image = sitk.Image(256, 128, 64, sitk.sitkInt16)
print(image.GetSize())

# Starting index of SimpleITK image is always 0
# Size of image's dimensions have explicit accessors

print(image.GetWidth())
print(image.GetHeight())
print(image.GetDepth())

# Can convert between numpy and SimpleITK
nda = sitk.GetArrayFromImage(image)
print(nda)

#mr_image = sitk.ReadImage('')

print(image.GetPixel(0,0,0))
image.SetPixel(0,0,0,1)
print(image.GetPixel(0,0,0))

#print(mr_image.GetPixel(100,100,100))

#n_mr_image = sitk.GetArrayFromImage(mr_image)
#print(n_mr_image)

z = 0
#slice = sitk.GetArrayViewFromImage(mr_image)[z,:,:]
#plt.imshow(slice)

# function to display 2D images in notebook
def myshow(img):
    nda = sitk.GetArrayViewFromImage(img)
    plt.imshow(nda)

# get a slice, and can do operations on them
#myshow(mr_image[:,:,80])
#myshow(mr_image[:,:,80]>0.5)



(256, 128, 64)
256
128
64
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
0
1


In [ ]:
# SimpleITK views images as physical objects occupying a bounded region in physical space
# Images can have different spacing between pixels along each axis
